require "jay.options"
require "jay.keymaps"
require "jay.plugins"
require "jay.colorscheme"
require "jay.cmp"
require "jay.lsp"
require "jay.telescope"
require "jay.treesitter"
require "jay.autopairs"
require "jay.comments"
require "jay.gitsigns"
require "jay.nvim-tree"
-- require "jay.bufferline"
require "jay.lualine"
require "jay.project"
require "jay.dashboard"
